version: '3.3'
services:
  magento.local:
    image: 'magento/magento-cloud-docker-varnish:latest'
    container_name: magento.local
    environment:
      - VIRTUAL_HOST=magento.local
      - VIRTUAL_PORT=80
    depends_on:
      - web
    ports:
      - '80:80'
  web:
    image: 'magento/magento-cloud-docker-nginx:latest'
    container_name: web
    volumes:
      - './html:/app'
      - './default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - fpm
  elasticsearch:
    image: 'magento/magento-cloud-docker-elasticsearch:6.5'
    container_name: elasticsearch
  mariadb:
    image: 'mariadb:10.2'
    container_name: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento_password
      - MYSQL_DATABASE=magento
#      - MYSQL_INITDB_SKIP_TZINFO=1
    volumes:
      - 'mariadb_data:/var/lib/mysql'
      - './html:/tmp/html'
      - './server.cnf:/etc/mysql/conf.d/server.cnf'
  fpm:
    image: 'magento/magento-cloud-docker-php:7.3-fpm'
    container_name: fpm
    environment:
      - PHP_MEMORY_LIMIT=2048M
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=magento
      - MAGENTO_DATABASE_PASSWORD=magento_password
      - MAGENTO_DATABASE_NAME=magento
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip redis xsl sodium'
    volumes:
      - './html:/app'
      - './files:/tmp/files'
      - './allure-report:/tmp/allure-report'
    depends_on:
      - mariadb
      - rabbitmq
      - redis
  selenium:
    image: 'selenium/standalone-chrome:3.141.59-xenon'
    container_name: selenium
    environment:
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=24
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - fpm
    ports:
      - "4444:4444"
  rabbitmq:
    image: 'rabbitmq:3.7'
    container_name: rabbitmq
    environment: 
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=128MiB
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq_password
  redis:
    image: 'magento/magento-cloud-docker-redis:5.0'
    container_name: redis
    volumes:
      - 'redis_data:/data'
    ports:
      - "6379:6379"
volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local
